Create comments model
LittleKidogo/quick_bytes_backend pull request #13
Opened 2018-08-09 17:34 UTC by br4inii

Fixes #8

## Proposed Changes

  - add comments table
  - add tests for the same
  -

2018-08-09 17:47 UTC, zacck-zz requested changes
Hey! this looks good!!

2018-08-09 17:47 UTC, zacck commented on priv/repo/migrations/20180809102052_create_comments.exs
> +      #add :manual_id, references(:manuals, type: :binary_id)
You can remove this since we will make a new migration to associate comments to manuals

2018-08-09 22:45 UTC, zacck-zz approved these changes

2018-08-10 06:32 UTC, zacck-zz requested changes
add tests for the manuals

2018-08-10 15:26 UTC, zacck-zz requested changes
@br4inii  @WanjikuMac  such awesome teamwork! just a little push to go over the hill

2018-08-10 15:26 UTC, zacck commented on test/support/factory.ex
> +      profile: build(:profile),
is this last comma needed?

2018-08-10 15:26 UTC, zacck commented on lib/qb_backend/posts/comment.ex
> +defmodule QbBackend.Posts.Comment do
please run mix format for all these changes

2018-08-10 15:26 UTC, zacck commented on lib/qb_backend/posts/posts.ex
> +  #Comments related functions
Is this comment needed ?

2018-08-10 15:26 UTC, zacck commented on test/lib/qb_backend/posts/posts_test.exs
> +  # Comment functions tests under Posts context
this comment is unneccessary as the code is very clear

2018-08-10 15:26 UTC, zacck commented on test/support/factory.ex
> +      profile: build(:profile),
is this last comma needed?

2018-08-10 15:27 UTC, br4inii commented on test/support/factory.ex
> +      profile: build(:profile),
not really,

2018-08-10 15:44 UTC, zacck-zz requested changes
Awesome work team @br4inii  @WanjikuMac

2018-08-10 15:44 UTC, zacck-zz approved these changes

2018-08-10 15:46 UTC, merged