Feature/create manual model
LittleKidogo/quick_bytes_backend pull request #15
Opened 2018-08-09 18:23 UTC by WanjikuMac

Fixes #7 
## Proposed Changes

  - Create the manual model
  -
  -

2018-08-09 22:47 UTC, zacck-zz reviewed
Hey @WanjikuMac  good swift work! I think a little change to push this over the hill

2018-08-09 22:47 UTC, zacck commented on test/lib/qb_backend/Posts/manual_test.exs
> +    Posts.Profile
is this used? I think it should be Accounts.Profile if it is

2018-08-10 13:40 UTC, r-coh reviewed
Awsome collabo !!!... @zacck thanks for this.

2018-08-10 13:41 UTC, zacck-zz requested changes
Just a few changes to push this over @br4inii

2018-08-10 13:41 UTC, zacck commented on test/lib/qb_backend/posts/manual_test.exs
> +    Posts.Profile
@br4inii  this is unused and can be removed

2018-08-10 13:41 UTC, zacck commented on test/lib/qb_backend/posts/posts_test.exs
> +       assert {:ok, %Manual{} = mnl} =  Posts.create_manual(profile, @valid_manual)
@br4inii  `mnl` here is not used so can be removed

2018-08-10 13:54 UTC, merged